<?php
$fieldDummy = "(NULL, 'Accounting'),
                                                    (NULL, 'Agriculture, fishing and forestry'),
                                                    (NULL, 'Architecture'),
                                                    (NULL, 'Automotive'),
                                                    (NULL, 'Banking, finance & insurance'),
                                                    (NULL, 'Construction & roading'),
                                                    (NULL, 'Customer service'),
                                                    (NULL, 'Education'),
                                                    (NULL, 'Engineering'),
                                                    (NULL, 'Executive & general management'),
                                                    (NULL, 'Government & council'),
                                                    (NULL, 'Healthcare'),
                                                    (NULL, 'Hospitality & tourism'),
                                                    (NULL, 'HR & recruitment'),
                                                    (NULL, 'IT'),
                                                    (NULL, 'Legal'),
                                                    (NULL, 'Manufacturing & operations'),
                                                    (NULL, 'Marketing, media & communications'),
                                                    (NULL, 'Office & administration'),
                                                    (NULL, 'Property'),
                                                    (NULL, 'Retail'),
                                                    (NULL, 'Sales'),
                                                    (NULL, 'Science & technology'),
                                                    (NULL, 'Trades & services'),
                                                    (NULL, 'Transport & logistics')
                                                    ;";
