<?php

$qualTypeDummy = "(NULL, 'Accountancy'),
                                                     (NULL, 'AgriCommerce'),
                                                     (NULL, 'Agricultural Science'),
                                                     (NULL, 'Applied Economics'),
                                                     (NULL, 'Arts'),
                                                     (NULL, 'Aviation'), 
                                                     (NULL, 'Aviation Management'), 
                                                     (NULL, 'Business'), 
                                                     (NULL, 'Commercial Music'), 
                                                     (NULL, 'Communication'), 
                                                     (NULL, 'Construction'), 
                                                     (NULL, 'Creative Media Production'), 
                                                     (NULL, 'Education'), 
                                                     (NULL, 'Health Science'), 
                                                     (NULL, 'Horticultural Science'), 
                                                     (NULL, 'Information Sciences'), 
                                                     (NULL, 'Maori Visual Arts'), 
                                                     (NULL, 'Nursing'), 
                                                     (NULL, 'Resource and Environmental Planning'), 
                                                     (NULL, 'Retail and Business Management'), 
                                                     (NULL, 'Science'), 
                                                     (NULL, 'Social Work'), 
                                                     (NULL, 'Sport and Exercise'), 
                                                     (NULL, 'Sport Management'), 
                                                     (NULL, 'Veterinary Science'), 
                                                     (NULL, 'Veterinary Technology');";
