
<?php 
include "header.phtml"
 ?>

<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
				<h2>Welcome <?= $candidateInfo->getGName()." ".$candidateInfo->getFName() ?>.</h2>
			</div>
			<div class="test">
				<br>

                <p>First Name: <?= $candidateInfo->getGName()?> </p>
                <p>Last Name: <?= $candidateInfo->getFName() ?> </p>
                <p>Username: <?= $candidateInfo->getUserName() ?></p>
                <p>Email: <?= $candidateInfo->getEmail() ?></p>
                <p>Phone number: <?= $candidateInfo->getPhoneNumber() ?></p>
                <p>Location: <?= $candidateInfo->getLocation() ?> </p>

                <div id="work-experience">
                    <p>Work Experience</p>
                    <?php $workExperience = $candidateInfo->getWorkExperience();
                    foreach ($workExperience as $work){
                        echo "<p>Role: ".$work->getRole()."</p>";
                        echo "<p>Duration (in months): ".$work->getDuration()."</p>";
                        echo "<p>Employer: ".$work->getEmployer()."</p>";
                    } ?>
                </div>

                <div id="qualifications">
                    <p>Qualifications</p>
                    <?php $qualifications = $candidateInfo->getQualifications();
                    foreach ($qualifications as $qual){
                        echo "<p>Year: ".$qual->getYear()."</p>";
                        echo "<p>Name: ".$qual->getName()."</p>";
                    } ?>
                </div>

                <div id="skills">
                    <p>Skills</p>
                    <?php $skills = $candidateInfo->getSkills();
                    foreach ($skills as $skill){
                        echo "<p>Field: ".$skill->getField()."</p>";
                        echo "<p>SubField: ".$skill->getSubField()."</p>";
                        echo "<p>Contents: ".$skill->getContents()."</p>";
                    } ?>
                </div>

                <?php
                $availability = $candidateInfo->getAvailability();
                $availabilityString = "";
                if($availability - 8 >= 0) {
                    $availability -= 8;
                    $availabilityString = $availabilityString."Contractor ";
                }
                if($availability - 4 >= 0) {
                    $availability -= 4;
                    $availabilityString = $availabilityString."Casual ";
                }
                if($availability - 2 >= 0) {
                    $availability -= 2;
                    $availabilityString = $availabilityString."Part Time ";
                }
                if($availability - 1 >= 0) {
                    $availabilityString = $availabilityString."Full Time";
                }
                echo "<p>Availability: ".$availabilityString."</p>";
                ?>

				<p>Click <a href="<?= $linkTo('editCandidateInfoPage'); ?>">Here</a> to edit info</p>
				<p>Click <a>Here</a> to view invites</p>
                <p>Click <a href="<?= $linkTo('logout'); ?>">Here</a> to logout</p>
			</div>
			<br>
			<br>
			
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>