<?php 
include "header.phtml"
 ?>
 <script type = "text/javascript" src="src/js/addRegistration.js"></script>
 <script type = "text/javascript" src="src/js/populateSubFields.js"></script>
 <script type = "text/javascript" src="src/js/candidateDelete.js"></script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class="container-fluid from-top from-bottom" id= "page">
        <div class ="partition large-box-format">
<!--            <div class="center">-->
<!--                <img id="logo" src="/static/styles/Images/VN.png">-->
<!--            </div>-->

            <div class="center">
                <h1>Edit Information</h1>
            </div>
	   <div id="registration">
            <form method="POST" name="registration" action="<?= $linkTo('updateCandidateData'); ?>" >
                <div class=" partition zebra large-box-format">
                    <div class="row center">
                        <h2 class="col-sm-11">Personal Information</h2>
                    </div>
                    <div class=" partition large-box-format">
                        <div class="form-group">
                            <label for="first-name">First Name: </label>
                            <input class="form-control" type="text"  placeholder="John" id="first-name"   name="first-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only" value="<?= $candidateInfo->getGName() ?>">
                        </div>
                        <div class="form-group">
                            <label for="last-name">Last Name: </label>
                            <input class="form-control"  type="text" placeholder="Smith" id="last-name" name="last-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only" value="<?= $candidateInfo->getFName() ?>">
                        </div>
                        <input hidden type="text" placeholder="Username"  name="username" size="40" required pattern="^[a-zA-Z0-9-_]+$" title="Alphanumeric, '-', and '_' characters only" value="<?= $candidateInfo->getUserName() ?>">
                        <div class="form-group">
                            <label for="email">Email: </label>
                            <input class="form-control"  type="text" placeholder="example@gmail.com" id="email" name="email" size="40" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" value="<?= $candidateInfo->getEmail() ?>">
                        </div>
                        <div class="form-group">
                            <label for="phone-number">Phone number: </label>
                            <input class="form-control"  type=text id="phone-number" name="phone-number" placeholder="Mobile and landlines accepted" size="40" required pattern="^[0-9+\s-]+$" title="Numeric, '+', '-' and space characters only" value="<?= $candidateInfo->getPhoneNumber() ?>">
                        </div>
                        <div class="form-group">
                            <label for="location">Location: </label>
                            <input class="form-control"  type=text id="location" name="location" placeholder="City" size="40" required pattern="^[a-zA-Z0-9\s,]+$" title="Alphanumeric and space characters only" value="<?= $candidateInfo->getLocation() ?>">
                        </div>
                    </div>
                </div>

                <div class="partition zebra large-box-format" id="work-experience">
                    <div class="row center">
                        <h2 class="col-sm-10">Work Experience</h2>
                        <input class="col-sm-1 btn btn-success" type="button" id="add-work-experience" value="Add" onclick="addWorkExperience()">
                    </div>
                    <?php $workExperience = $candidateInfo->getWorkExperience();
                    $i = 0;

                    foreach ($workExperience as $work){
                        $id = $work->getId();
                        echo "<div id = \"workExperience".$i."\" class = \"edit-box partition interior-box-format\">";
                        echo "<input class=\"btn btn-danger\" type=\"button\" id=\"delete-work-experience".$i."\" value = \"Delete\" onclick=\"deleteWorkExperience(".$i.", ".$id.")\">";

                        $role = "role".$i;
                        $duration = "duration".$i;
                        $employer = "employer".$i;
                        $workId = "weid".$i;
                        $workId2 = "workId".$i;
                        if($candidateInfo->getPreferredWorkExperience() != $id) {
                            echo "<div class=\"sm-pad form-group\"><label for=\"work-experience-preference".$i."\">Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id=\"work-experience-preference".$i."\" name='work-experience-preference'></div>";
                        } else {
                            echo "<div class=\"sm-pad form-group\"><label for=\"work-experience-preference".$i."\">Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id=\"work-experience-preference".$i."\" name='work-experience-preference' checked></div>";
                        }
                        echo "<div class=\"form-group\"><label for=\"".$role."\">Role: </label><input placeholder='Alphabetic characters only' class=\"form-control\" type=text name=\"".$role."\" id=\"".$role."\" size=\"40\" pattern=\"^[a-zA-Z\s-]+$\" title=\"Alphabetic, '-' and space characters only\" value =\"".$work->getRole() ."\"></div> ";
                        echo "<div class=\"form-group\"><label for=\"".$duration."\">Duration : </label><input placeholder='Number in months' class=\"form-control\" type=text name=\"".$duration."\" id=\"".$duration."\" size=\"40\" pattern=\"^[0-9]+$\" title=\"Numeric characters only\" value=\"".$work->getDuration()."\"></div>";
                        echo "<div class=\"form-group\"><label for=\"".$employer."\">Employer: </label><input placeholder='Alphanumeric characters only' class=\"form-control\" type=text name=\"".$employer."\" id=\"".$employer."\" size=\"40\" pattern=\"^[a-zA-Z0-9\s-]+$\" title=\"Alphanumeric, '-' and space characters only\" value= \"".$work->getEmployer()."\"></div> ";
                        echo "<input type = \"hidden\" name=\"".$workId."\" id=\"".$workId2."\" value=\"".$id."\">";
                        $i++;
                        echo "</div>";
                    }

                    $i--;
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"work-experience-existing-count\" id=\"work-experience-existing-count\">";
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"work-experience-count\" id=\"work-experience-count\">"?>


                </div>

                <div class="partition zebra large-box-format"  id="qualifications">
                    <div class="row center">
                        <h2 class="col-sm-10">Qualifications</h2>
                        <input class="col-sm-1 btn btn-success" type="button" id="add-qualification" value="Add" onclick="addQualification()">
                    </div>
                    <?php $qualifications = $candidateInfo->getQualifications();
                    $i = 0;
                    foreach ($qualifications as $qual){
                        echo "<div id = \"qualification".$i."\" class = \"edit-box partition interior-box-format\">";
                        $id = $qual->getId();
                        echo "<input class=\"btn btn-danger\" type=\"button\" id=\"delete-qualification".$i."\" value = \"Delete\" onclick=\"deleteQualification(".$i.", ".$id.")\">";
                        $allLevels = $qual->getLevels();
                        $allTypes = $qual->getTypes();
                        $year = "year".$i;
                        $level = "level".$i;
                        $type = "type".$i;
                        $major = "major".$i;
                        $qualId = "qid".$i;
                        $qualId2 = "qualId".$i;


                        if($candidateInfo->getPreferredQualification() != $id) {
                            echo "<div class=\"sm-pad form-group\"><label for='qualification-preference" . $i . "'>Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id='qualification-preference" . $i . "' name='qualification-preference'></div>";
                        } else {
                            echo "<div class=\"sm-pad form-group\"><label for='qualification-preference" . $i . "'>Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id='qualification-preference" . $i . "' name='qualification-preference' checked></div>";
                        }

                        $levelID = $qual->getLevelId();
                        echo "<div class=\"form-group\"><label for='".$level."'>Level:</label><select class=\"form-control\" id=\"".$level."\" name=\"".$level."\">";

                        foreach ($allLevels as $Level) {
                            echo "<option value=\"" . $Level['id'] . "\"";
                            if($levelID == $Level['id']){
                                echo " selected";
                            }
                            echo ">" . $Level['level'] . "</option>";
                        }
                        echo "</select></div>";


                        $typeID = $qual->getTypeId();
                        echo "<div class=\"form-group\"><label for='".$type."'>Field:</label><select class=\"form-control\" id=\"".$type."\" name=\"".$type."\">";

                        foreach ($allTypes as $Type) {
                            echo "<option value=\"" . $Type['id'] . "\"";
                            if($typeID == $Type['id']){
                                echo " selected";
                            }
                            echo ">" . $Type['type'] . "</option>";
                        }
                        echo "</select></div>";
                        $id = $qual->getId();
                        echo "<div class=\"form-group\"><label for='".$year."'>Year: </label><input placeholder='Year of completion' class=\"form-control\" type=text name=\"".$year."\" id=\"".$year."\" size=\"40\" pattern=\"^[0-9]{4}$\" title=\"YYYY format. Numeric characters only\" value=\"".$qual->getYear()."\"></div>";
                        echo "<div class=\"form-group\"><label for='".$major."'>Major: </label><input placeholder='E.g. Marketing' class=\"form-control\" type=text name=\"".$major."\" id=\"".$major."\" size=\"40\" value=\"".$qual->getMajor()."\"></div>";
                        echo "<input type = \"hidden\" name=\"".$qualId."\"  value=\"".$id."\">";
                        $i++;
                        echo "</div>";
                    }

                    $i--;
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"qualification-existing-count\" id=\"qualification-existing-count\">";
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"qualification-count\" id=\"qualification-count\">"?>

                </div>


                <div class="partition zebra large-box-format" id="skills">
                    <div class="row center">
                        <h2 class="col-sm-10">Skills</h2>
                        <input class="col-sm-1 btn btn-success" type="button" id="add-skill" value="Add" onclick="addSkill()">
                    </div>
                    <?php $skills = $candidateInfo->getSkills();
                    $i = 0;

                    foreach ($skills as $skill){
                        echo "<div id = \"skill".$i."\" class = \"edit-box partition interior-box-format\">";
                        $id = $skill->getId();
                        echo "<input class=\"btn btn-danger\" type=\"button\" id=\"delete-skill".$i."\" value = \"Delete\" onclick=\"deleteSkill(".$i.", ".$id.")\">";

                        if($candidateInfo->getPreferredSkill() != $id) {
                            echo "<div class=\"sm-pad form-group\"><label for='skill-preference".$i."'>Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id='skill-preference".$i."' name='skill-preference'></div>";
                        } else {
                            echo "<div class=\"sm-pad form-group\"><label for='skill-preference".$i."'>Preferred: </label><input class='pull-right' type=radio value=\"" . $i . "\" id='skill-preference".$i."' name='skill-preference' checked></div>";
                        }


                        $Fields = $skill->getFields();
                        $skillId = "sid".$i;
                        $skillId2 = "skillId".$i;
                        $name = "field".$i;
                        $fieldID = $skill->getFieldID($skill->getField());
                        echo "<div class=\"form-group\"><label for='".$name."'>Field</label><select class='form-control' id=\"".$name."\" name=\"".$name."\" onclick=\"updateFields(this);\">";

                        foreach ($Fields as $field) {
                            echo "<option value=\"" . $field['id'] ."\"";
                            if($fieldID == $field['id']){
                                echo " selected";
                            }
                            echo ">" . $field['field']."</option>";
                        }
                        echo "</select></div>";
                        $id = $skill->getFieldID($skill->getField());
                        $subFields = $skill->getSubFields($id);
                        $name = "sub-field".$i;
                        $subFieldID = $skill->getSubFieldID($skill->getSubField());
                        echo "<div class=\"form-group\"><label for='".$name."'>Sub-Field</label><select class='form-control' name=\"".$name."\" id=\"".$name."\">";
                        foreach ($subFields as $sub) {
                            echo "<option value=\"" . $sub['id'] ."\"";
                            if($subFieldID == $sub['id']){
                                echo " selected";
                            }
                            echo ">" . $sub['sub_field'] . "</option>";
                        }
                        echo "</select></div>";
                        $name = "contents".$i;
                        echo "<div class=\"form-group\"><label for='skill-input".$i."'>About: </label><input placeholder='Alphanumeric characters only' class='form-control' type=text id='skill-input".$i."' name=\"".$name."\" size=\"40\" pattern='^[a-zA-Z0-9\s-]+$' title=\"Alphanumeric, '-' and space characters only\" value=\"".$skill->getContents()."\"></div>";
                        echo "<input type = \"hidden\" name=\"".$skillId."\" value=\"".$skill->getId()."\">";
                        $i++;
                        echo "</div>";
                    }
                    $i--;
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"skill-existing-count\" id=\"skill-existing-count\">";
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"skill-count\" id=\"skill-count\">";
                    ?>

                </div>


                <div class="partition zebra large-box-format" id="availability" name="availability">
                    <div class="row center">
                        <h2 class="col-sm-11">Availability</h2>

                    </div>

                    <div class="partition large-box-format">
                        <div class="row center">
                            <p>Please check the options you are available for.</p>
                        </div>
                    <?php
                    $availability = $candidateInfo->getAvailability();
                    $availabilityString = "";
                    if($availability - 8 >= 0) {
                        $availability -= 8;
                        $availabilityString = $availabilityString."Full Time ";
                        echo "<div><input type=\"checkbox\" value=\"fullTime\" name=\"full-time\" id=\"full-time\" checked>";
                    }else{
                        echo "<div><input type=\"checkbox\" value=\"fullTime\" name=\"full-time\" id=\"full-time\">";
                    }
                    echo "<label class='checkbox-inline' for=\"fullTime\">Full Time</label></div>";
                    if($availability - 4 >= 0) {
                        $availability -= 4;
                        $availabilityString = $availabilityString."Part Time";
                        echo "<div><input type=\"checkbox\" value=\"partTime\" name=\"part-time\" id=\"part-time\" checked>";
                    }else{
                        echo "<div><input type=\"checkbox\" value=\"partTime\" name=\"part-time\" id=\"part-time\">";
                    }
                    echo "<label class='checkbox-inline' for=\"partTime\">Part Time</label></div>";
                    if($availability - 2 >= 0) {
                        $availability -= 2;
                        $availabilityString = $availabilityString."Casual";
                        echo "<div><input type=\"checkbox\" value=\"casual\" name=\"casual\" id=\"casual\" checked>";
                    }else{
                        echo "<div><input type=\"checkbox\" value=\"casual\" name=\"casual\" id=\"casual\">";
                    }
                    echo "<label class='checkbox-inline' for=\"casual\">Casual</label></div>";
                    if($availability - 1 >= 0) {
                        $availabilityString = $availabilityString."Contractor";
                        echo "<div><input type=\"checkbox\" value=\"contractor\" name=\"contractor\" id=\"contractor\" checked>";
                    }else{
                        echo "<div><input type=\"checkbox\" value=\"contractor\" name=\"contractor\" id=\"contractor\">";
                    }
                    echo "<label class='checkbox-inline' for=\"contractor\">Contractor</label></div>";
                    ?>
                    </div>
            </div>

        </div>


        <p type="hidden" id="validate"></p>

        <input class="btn btn-success btn-block btn-lrg" id="submit-handle" type="submit" >
    </form>
        </div>
    </div>
	<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>