
<?php 
include "header.phtml"
 ?>

<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class="container-fluid from-top from-bottom" id= "page">
        <div class="info">

    		<div class="partition large-box-format">
                <div class="title">
                    <h2 class="text-center">Page of <?= $candidateInfo->getGName()." ".$candidateInfo->getFName() ?>.</h2>
                </div>
                <p>First Name: <?= $candidateInfo->getGName()?> </p>
                <p>Last Name: <?= $candidateInfo->getFName() ?> </p>
                <p>Username: <?= $candidateInfo->getUserName() ?></p>
                <p>Email: <?= $candidateInfo->getEmail() ?></p>
                <p>Phone number: <?= $candidateInfo->getPhoneNumber() ?></p>
                <p>Location: <?= $candidateInfo->getLocation() ?> </p>

                <?php
                    $availability = $candidateInfo->getAvailability();
                    $availabilityString = "";
                    if($availability - 8 >= 0) {
                        $availability -= 8;
                        $availabilityString = $availabilityString."Full Time ";
                    }
                    if($availability - 4 >= 0) {
                        $availability -= 4;
                        $availabilityString = $availabilityString."Part Time ";
                    }
                    if($availability - 2 >= 0) {
                        $availability -= 2;
                        $availabilityString = $availabilityString."Casual ";
                    }
                    if($availability - 1 >= 0) {
                        $availabilityString = $availabilityString."Contractor";
                    }
                    echo "<p>Availability: ".$availabilityString."</p>";
                ?>
            </div>
        </div>
        <div id="work-experience " class ="partition large-box-format">
            <h2 class="text-center">Work Experience</h2>
            <?php $workExperience = $candidateInfo->getWorkExperience();
            foreach ($workExperience as $work){
                echo "<div class=\"row center\">";
                echo "<div class=\"partition col-sm-3 interior-box-format\">";
                echo "<p>Role: ".$work->getRole()."</p>";
                echo "<p>Duration (in months): ".$work->getDuration()."</p>";
                echo "<p>Employer: ".$work->getEmployer()."</p>";
                echo "</div>";
                echo "</div>";
            }
            ?>
        </div>

        <div id="qualifications " class ="partition large-box-format">
            <h2 class="text-center">Qualifications</h2>
            <?php $qualifications = $candidateInfo->getQualifications();
            foreach ($qualifications as $qual){
                echo "<div class=\"row center\">";
                echo "<div class=\"partition col-sm-3 interior-box-format\">";
                echo "<p>Level: ".$qual->findLevel($qual->getLevelId())."</p>";
                echo "<p>Type: ".$qual->findType($qual->getTypeId())."</p>";
                echo "<p>Major: ".$qual->getMajor()."</p>";
                echo "<p>Year: ".$qual->getYear()."</p>";
                echo "</div>";
                echo "</div>";
            }
            ?>
        </div>

        <div id="skills" class ="partition large-box-format">
            <h2 class="text-center">Skills</h2>
            <?php $skills = $candidateInfo->getSkills();
            foreach ($skills as $skill){
                echo "<div class=\"row center\">";
                echo "<div class=\"partition col-sm-3 interior-box-format\">";
                echo "<p>Field: ".$skill->getField()."</p>";
                echo "<p>SubField: ".$skill->getSubField()."</p>";
                echo "<p>Contents: ".$skill->getContents()."</p>";
                echo "</div>";
                echo "</div>";
            }
            ?>
        </div>
	</div>

	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>