<?php 
include "header.phtml"
 ?>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
			<h2>Candidate Registration Form</h2>
			</div>
                  <p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p> 


		   <div id="registration">
        <form method="POST" name="registration" action="<?= $linkTo('registrationConfirmationPage'); ?>" >
            <p>Name: <input type="text" placeholder="Name" name="name" size="40" pattern="^[a-zA-Z0-9\s]+$" title="Alphanumeric characters and spaces only"> </p>
            <p>Username: <input type="text" placeholder="Username"  name="username" size="40" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only" ></p>
            <p>Email: <input type="text" placeholder="Email" name="email" size="40" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" ></p>
            <p>Password: <input type="password" placeholder="Password" name="password" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" > </p>
            <p>Confirm Password: <input type="password" placeholder="Password" name="password_confirm" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" ></p>

            <p>Phone number: <input type=text name="phoneNumber" size="40" required pattern="^[0-9+]+$" title="Numeric characters only"> </p>
            <p>Location: <input type=text name="location" size="40" required pattern="^[a-zA-Z]+$" title="Alphabetic characters only"> </p>
            <p>Skill: <input type=text name="skill" size="40" required pattern="^[a-zA-Z,]+$" title="Comma separated list"> </p> <!-- Need to expand this for list of skills -->

            <p>Work Experience</p>
            <p>Duration: <input type=text name="duration" size="40"> </p>       <!-- Drop down -->
            <p>Role: <input type=text name="role" size="40" required pattern="^[a-zA-Z]+$" title="Alphabetic characters only"> </p>
            <p>Employer: <input type=text name="employer" size="40" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only"> </p>


            <p>Qualifications</p>
            <p>Year: <input type=text name="year" size="40"> </p>       <!-- Drop down -->
            <p>Major: <input type=text name="major" size="40" required pattern="^[a-zA-Z]+$" title="Alphabetic characters only"> </p>

            </div>
            <p type="hidden" id="validate"></p>
           <!-- <button id="submit-registration" value="Register" onclick="return validateForm()">Register</button> -->
            <input id="submit-handle" type="submit" style="display: none">
        </form>
		    <br>
                <p>Click <a href="<?= $linkTo('registrationConfirmationPage'); ?>">Here</a> to go to the next page(temp)</p> 	
			
		</div>
	</div>
	<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>