<?php
include "header.phtml"
?>
    <script type = "text/javascript" src="src/js/validateForm.js"></script>


    <!---------- Body starts --------------->


    <!--- Content Start -->
    <div class="container-fluid from-top center" id= "page">

        <div class="box-tight partition large-box-format" id="registration">


            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>

            <div class="center">
                <h4>Candidate Registration</h4>
            </div>

            <form class="form-pad form-horizontal" method="POST" name="registration" action="<?= $linkTo('submitCandidateRegistration'); ?>" >
                <div class="form-group">
                    <label for="first-name">First Name:</label>
                    <input class="form-control" type="text" placeholder="John" id="first-name" name="first-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only">
                </div>
                <div class="form-group">
                    <label for="last-name">Last Name:</label>
                    <input class="form-control"  type="text" placeholder="Smith" id="last-name" name="last-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only">
                </div>
                <div class="form-group">
                    <label for="username">Username: </label>
                    <input class="form-control"  type="text" placeholder="Must be between 5-15 characters" id="username"  name="username" size="40" required pattern="^[a-zA-Z0-9-_]+$" title="Alphanumeric, '-', and '_' characters only" >
                </div>
                <div class="form-group">
                    <label for="email">Email: </label>
                    <input class="form-control"  type="text" placeholder="example@gmail.com" id="email" name="email" size="40" required pattern="[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" >
                </div>
                <div class="form-group">
                    <label for="password">Password: </label>
                    <input class="form-control"  type="password" placeholder="At least 7 characters and must contain 1 uppercase letter" id="password" name="password" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" >
                </div>
                <div class="form-group">
                    <label for="password_confirm">Confirm Password: </label>
                    <input class="form-control"  type="password" placeholder="Retype password" id="password_confirm" name="password_confirm" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" >
                </div>
                <div class="form-group">
                    <label for="phone-number">Phone number: </label>
                    <input class="form-control"  type=text id="phone-number" name="phone-number" placeholder="Mobile and landlines accepted" size="40" required pattern="^[0-9+\s-]+$" title="Numeric, '+', '-' and space characters only">
                </div>
                <div class="form-group">
                    <label for="location">Location: </label>
                    <input class="form-control"  type=text id="location" name="location" placeholder="City" size="40" required pattern="^[a-zA-Z0-9\s,]+$" title="Alphanumeric and space characters only">
                </div>
                <p type="hidden" id="validate"></p>
                <div class="center">
                    <button class="btn btn-info" id="submit-registration" value="Register" onclick="return validateForm()">Register</button>
                </div>
                <input id="submit-handle" type="submit" style="display: none">
            </form>
        </div>

    </div>
    <!--- Content Ends here ----------->




    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>