<?php 
include "header.phtml"
 ?>
 <script type = "text/javascript" src="src/js/addRegistration.js"></script>
 <script type = "text/javascript" src="src/js/populateSubFields.js"></script>
 <script type = "text/javascript" src="src/js/candidateDelete.js"></script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
			<h2>Edit your information here:</h2>
			</div>

		   <div id="registration">
                <form method="POST" name="registration" action="<?= $linkTo('updateCandidateData'); ?>" >
                <p>First Name: <input type="text" placeholder="Name" name="first-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only" value="<?= $candidateInfo->getGName() ?>"> </p>
                <p>Last Name: <input type="text" placeholder="Name" name="last-name" size="40" pattern="^[a-zA-Z-\s]+$" title="Alphabetic, '-' characters and spaces only" value="<?= $candidateInfo->getFName() ?>"> </p>
                <input hidden type="text" placeholder="Username"  name="username" size="40" required pattern="^[a-zA-Z0-9-_]+$" title="Alphanumeric, '-', and '_' characters only" value="<?= $candidateInfo->getUserName() ?>">
                <p>Email: <input type="text" placeholder="Email" name="email" size="40" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" value="<?= $candidateInfo->getEmail() ?>"></p>

                <p>Phone number: <input type=text name="phone-number" size="40" required pattern="^[0-9+\s-]+$" title="Numeric, '+', '-' and space characters only" value="<?= $candidateInfo->getPhoneNumber() ?>"> </p>
                <p>Location: <input type=text name="location" size="40" required pattern="^[a-zA-Z0-9\s]+$" title="Alphanumeric and space characters only" value="<?= $candidateInfo->getLocation() ?>"> </p>

                <div id="work-experience">
                    <p>Work Experience</p>
                    <?php $workExperience = $candidateInfo->getWorkExperience();
                    $i = 0;

                    foreach ($workExperience as $work){
                        $id = $work->getID();
                        echo "<div id = \"workExperience".$i."\">";
                        echo "<input type=\"button\" id=\"delete-work-experience\"".$i." value = \"Delete\" onclick=\"deleteWorkExperience(".$i.", ".$id.")\">";

                        $role = "role".$i;
                        $duration = "duration".$i;
                        $employer = "employer".$i;
                        $workId = "id".$i;
                        $workId2 = "workId".$i;
                        echo "<p>Role: <input type=text name=\"".$role."\" id=\"".$role."\" size=\"40\" pattern=\"^[a-zA-Z\s-]+$\" title=\"Alphabetic, '-' and space characters only\" value =\"".$work->getRole() ."\"> </p>";
                        echo "<p>Duration (in months): <input type=text name=\"".$duration."\" id=\"".$duration."\" size=\"40\" pattern=\"^[0-9]+$\" title=\"Numeric characters only\" value=\"".$work->getDuration()."\"> </p>";
                        echo "<p>Employer: <input type=text name=\"".$employer."\" id=\"".$employer."\" size=\"40\" pattern=\"^[a-zA-Z0-9\s-]+$\" title=\"Alphanumeric, '-' and space characters only\" value= \"".$work->getEmployer()."\"> </p>";
                        echo "<input type = \"hidden\" name=\"".$workId."\" id=\"".$workId2."\" value=\"".$work->getId()."\">";
                        $i++;
                        echo "</div>";
                    }

                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"work-experience-count\" id=\"work-experience-count\">"?>
                </div>
                <input type="button" id="add-work-experience" value="Add" onclick="addWorkExperience()">

                <div id="qualifications">
                    <p>Qualifications</p>
                    <?php $qualifications = $candidateInfo->getQualifications();
                    $i = 0;
                    foreach ($qualifications as $qual){
                        echo "<div id = \"qualification".$i."\">";
                        $id = $qual->getID();
                        echo "<input type=\"button\" id=\"delete-qualification\"".$i." value = \"Delete\" onclick=\"deleteQualification(".$i.", ".$id.")\">";
                        $year = "year".$i;
                        $name = "name".$i;
                        $qualId = "id".$i;
                        $qualId2 = "qualId".$i;
                        echo "<p>Name: <input type=text name=\"".$name."\" id=\"".$name."\" size=\"40\" pattern=\"^[a-zA-Z\s-]+$\" title=\"Alphabetic, '-' and space characters only\" value=\"".$qual->getName()."\"> </p>";
                        echo "<p>Year: <input type=text name=\"".$year."\" id=\"".$year."\" size=\"40\" pattern=\"^\d{4}$\" title=\"YYYY format. Numeric characters only\" value=\"".$qual->getYear()."\"> </p>";
                        echo "<input type = \"hidden\" name=\"".$qualId."\" name=\"".$qualId2."\" value=\"".$qual->getId()."\">";
                        $i++;
                        echo "</div>";
                    }
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"qualification-count\" id=\"qualification-count\">"?>
                </div>
                <input type="button" id="add-qualification" value="Add" onclick="addQualification()">

                <div id="skills">
                    <p>Skills</p>
                    <?php $skills = $candidateInfo->getSkills();
                    $i = 0;

                    foreach ($skills as $skill){
                        echo "<div id = \"skill".$i."\">";
                        $id = $skill->getID();
                        echo "<input type=\"button\" id=\"delete-skill\"".$i." value = \"Delete\" onclick=\"deleteSkill(".$i.", ".$id.")\">";
                        echo "<p>Field</p>";
                        $Fields = $skill->getFields();
                        $skillId = "id".$i;
                        $skillId2 = "skillId".$i;
                        $name = "field".$i;
                        echo "<select id=\"".$name."\" name=\"".$name."\" onclick=\"updateFields(this);\" selected = \"".$skill->getField()."\">";

                        foreach ($Fields as $field) {
                            echo "<option value=\"" . $field['id'] . "\">" . $field['field'] . "</option>";
                        }
                        echo "</select>";
                        $id = $skill->getFieldID($skill->getField());
                        $subFields = $skill->getSubFields($id);
                        $name = "sub-field".$i;
                        echo "<p>Sub-Field:  </p>";
                        echo "<select name=\"".$name."\" id=\"".$name."\" selected=\"".$skill->getSubField()."\">";
                        foreach ($subFields as $sub) {
                            echo "<option value=\"" . $sub['id'] . "\">" . $sub['sub_field'] . "</option>";
                        }
                        echo "</select>";
                        $name = "contents".$i;
                        echo "<p>About: <input type=text name=\"".$name."\" size=\"40\" pattern=\"^[a-zA-Z\s-]+$\" title=\"Alphabetic, '-' and space characters only\" value=\"".$skill->getContents()."\">";
                        echo "<br>";
                        echo "<input type = \"hidden\" name=\"".$skillId."\" id=\"".$skillId2."\" value=\"".$skill->getId()."\">";
                        $i++;
                        echo "</div>";
                    }
                    echo "<input type=\"hidden\" value=\"".$i."\" name=\"skill-count\" id=\"skill-count\">";
                    ?>

                </div>
                <input type="button" id="add-skill" value="Add" onclick="addSkill()">


                    <div id="availability" name="availability">
                        <p>Availability</p>
                    <?php
                    $availability = $candidateInfo->getAvailability();
                    $availabilityString = "";
                    if($availability - 8 >= 0) {
                        $availability -= 8;
                        $availabilityString = $availabilityString."Full Time ";
                        echo "<input type=\"checkbox\" value=\"fullTime\" name=\"full-time\" id=\"full-time\" checked>";
                    }else{
                        echo "<input type=\"checkbox\" value=\"fullTime\" name=\"full-time\" id=\"full-time\">";
                    }
                    echo "<label for=\"fullTime\">Full Time</label>";
                    if($availability - 4 >= 0) {
                        $availability -= 4;
                        $availabilityString = $availabilityString."Part Time";
                        echo "<input type=\"checkbox\" value=\"partTime\" name=\"part-time\" id=\"part-time\" checked>";
                    }else{
                        echo "<input type=\"checkbox\" value=\"partTime\" name=\"part-time\" id=\"part-time\">";
                    }
                    echo "<label for=\"partTime\">Part Time</label>";
                    if($availability - 2 >= 0) {
                        $availability -= 2;
                        $availabilityString = $availabilityString."Casual";
                        echo "<input type=\"checkbox\" value=\"casual\" name=\"casual\" id=\"casual\" checked>";
                    }else{
                        echo "<input type=\"checkbox\" value=\"casual\" name=\"casual\" id=\"casual\">";
                    }
                    echo "<label for=\"casual\">Casual</label>";
                    if($availability - 1 >= 0) {
                        $availabilityString = $availabilityString."Contractor";
                        echo "<input type=\"checkbox\" value=\"contractor\" name=\"contractor\" id=\"contractor\" checked>";
                    }else{
                        echo "<input type=\"checkbox\" value=\"contractor\" name=\"contractor\" id=\"contractor\">";
                    }
                    echo "<label for=\"contractor\">Contractor</label>";
                    ?>

                </div>

            </div>


            <p type="hidden" id="validate"></p>

            <input id="submit-handle" type="submit" >
        </form>
		    <br>

		</div>
        <p>Click <a href="<?= $linkTo('candidateHomePage'); ?>">Here</a> to return home.</p>
    </div>
	<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>