
<?php
include "header.phtml"
 ?>
<script type = "text/javascript" src="src/js/employerEdit.js"></script>
<script type = "text/javascript" src="src/js/livesearch.js"></script>
<script type = "text/javascript" src="src/js/updateShortList.js"></script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class="container-fluid from-top">
        <div class="#" id="welcome">
            <div class= "row">
                <div class = "title col-sm-4">
                    <h2>Welcome <?= $employerInfo->getContactName()?>.</h2>
                </div>
                <div class="col-sm-8 text-right" id="personal-info">
                    <p>Company Name: <?= $employerInfo->getCompanyName() ?> </p>
                    <p>Location: <?= $employerInfo->getAddress() ?></p>
                    <p>URL: <?= $employerInfo->getURL() ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="separator"><br></div>

    <div class="container-fluid" id= "page">
        <div id="short-lists" class="shortlists">
            <?php $shortLists = $employerInfo->getShortLists();
            $i = 0;
//            if($employerInfo->numOfShortlists() == 0){
//                error_log("here");
//                echo "<div class=\"partition\"> ";
//                echo "<h4>No shortlists added.</h4>";
//                // Add button to add a shortlist here
//                echo "</div>";
//            }
            $candCount = 0;
            foreach ($shortLists as $list){


                echo "<div class=\"partition shortlist-format\" id=\"shortlist".$i."\">";
                echo "<div class=\"row\">";
                echo "<h3 id = \"shortList".$i."\" class=\"col-sm-9 font-weight-bold\"><u>".$list->getName()."</u></h3>";
                if($list->isHasInvited()) {
                    echo "<input type=\"button\" value=\"Invites sent\" name=\"sendInvites\" disabled   >";
                }else{
                    echo "<p><a  class=\"btn btn-info col-sm-2\" id=\"send-invite-btn\" href=\"writeEmail.php?list_id=".$list->getId()."\">Send Invite Email</a></p>";
                }
                echo "</div>";
                echo "<input type=\"button\" id=\"delete".$i."\" value = \"Delete\" onclick = \"deleteShortList(".$i.", ".$list->getId().")\">";
                echo "<input type=\"button\" id=\"re-name".$i."\" value = \"Re-name\" onclick=\"renameList(".$i.", ".$list->getId().")\">";
                echo "<input type=\"button\" id=\"change-description".$i."\" value = \"Change Description\" onclick=\"changeDescription(".$i.", ".$list->getId().")\">";
                echo "<input type=\"hidden\" id=\"shortlist".$i."\" value=\"".$list->getId()."\" >";
                echo "<input type=\"hidden\" id=\"num".$i."\" value=\"".$candCount."\" >";
                echo "<p size = \"512\" id = \"shortListDescription".$i."\">Description: ".$list->getDescription()."</p>";
                echo "<h4 class=\"font-weight-bold\"> Candidates: </h4>";
                $candidates = $list->getCandidates();
                echo "<div class=\"row\">";
                $count = 0;
                echo "<div id=\"candidates".$i."\">";
                foreach ($candidates as $candidate) {
                    if($count == 4){
                        echo "</div><div class=\"row\">";
                        $count = 0;
                    }
                    $candID = "cand" . $candCount;
                    if($candidate->getGName() != NULL) {
                        echo "<p id = \"" . $candID . "\" class=\"col-sm-3\"><a href=\"View-Candidate\" onclick=\"return displayCandidate('View-Candidate',".$candidate->getUserId().")\">" . $candidate->getGName() . "</a> " . $candidate->getFName() . "<input type=\"button\" id=\"deleteCandidate" . $candCount . "\" value = \"-\" onclick=\"deleteFromShortList(" . $list->getId() . ", " . $candidate->getId() . ", " . $candCount . ", ".$i.")\"></p>";
                        $candCount++;
                    }

                    $count++;
                }
                echo "</div>";
                echo "</div>";
                echo "</div>";
                $i++;
            }
            echo "<input type=\"button\" id=\"newList\" value = \"Add\" onclick=\"newShortList(".$employerInfo->getId().",".$i.")\">";
            ?>
        </div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>