
<?php 
include "header.phtml"
 ?>

<script type = "text/javascript" src="src/js/validateForm.js"></script>
<script type = "text/javascript" src="src/js/employerEdit.js"></script>
<script type = "text/javascript" src="src/js/updateShortList.js"></script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
				<h2>Edit your information here:</h2>
			</div>


		<div id="registration">
        <form method="POST" name="registration" action="<?= $linkTo('updateEmployerData'); ?>" >
            <input type="text" placeholder="Username"  name="username" size="40" hidden value="<?= $employerInfo->getUserName() ?>">
            <p>Email: <input type="text" placeholder="Email" name="email" size="40" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" value="<?= $employerInfo->getEmail() ?>"></p>

            <p>Phone number: <input type=text name="phone-number" size="40" required pattern="^[0-9+-\s]+$" title="Numeric, '+', '-', and space characters only" value="<?= $employerInfo->getPhoneNumber() ?>"> </p>
            <p>Address: <input type=text name="address" size="40" required pattern="^[a-zA-Z0-9\s]+$" title="Alphanumeric characters and spaces only" value="<?= $employerInfo->getAddress() ?>"> </p>

            <p>Company Name: <input type=text name="company-name" size="40" required pattern="^[a-zA-Z0-9\s-]+$" title="Alphanumeric, '-' and space characters only" value="<?= $employerInfo->getCompanyName() ?>"> </p>
            <p>URL: <input type=text name="url" size="40" value="<?= $employerInfo->getURL() ?>"> </p>
            <p>Contact Name: <input type=text name="contact-name" size="40" required pattern="^[a-zA-Z\s]+$" title="Alphabetic characters and spaces only" value="<?= $employerInfo->getContactName() ?>"> </p>
            <p>Calendar Link: <input type=text name="calendar-link" size="256" value="<?= $employerInfo->getCalendarLink() ?>"> </p>

            </div>
          <!--  <button id="submit-registration" value="Update" onclick="return validateForm()">Update</button>  not sure why this is here?-->
            <input id="submit-handle" type="submit" >
        </form>

		    <br>
			
		</div>
        <p>Short Lists</p>
        <div id="short-lists">

            <?php
            $shortLists = $employerInfo->getShortLists();
            $i = 0;
            $candcount = 0;
            foreach ($shortLists as $list){
                echo " <div id =\"shortlist".$i."\" class=\"partition\">";
                $listID = $list->getID();
                echo "<input type=\"button\" id=\"delete".$i."\" value = \"Delete\" onclick = \"deleteShortList(".$i.", ".$listID.")\">";
                echo "<input type=\"button\" id=\"re-name".$i."\" value = \"Re-name\" onclick=\"renameList(".$i.", ".$listID.")\">";
                echo "<p id = \"shortList".$i."\">".$list->getName()."</p>";
                $candidates = $list->getCandidates();
                foreach ($candidates as $candidate){
                    if($candidate->getGName() != NULL) {
                        $candID = "cand" . $candcount;
                        $candidateID = $candidate->getID();
                        echo "<p id = \"" . $candID . "\">Name: " . $candidate->getGName() . " " . $candidate->getFName() ."<input type=\"button\" id=\"deleteCandidate" . $candcount . "\" value = \"-\" onclick=\"deleteFromShortList(" . $listID . ", " . $candidateID . ", " . $candcount . "," . $i . ")\"> </p> ";

                        $candcount++;
                    }
                }
                $i++;
                echo " </div>";
            }
            echo "<input type=\"button\" id=\"newList\" value = \"Add\" onclick=\"newShortList(".$employerInfo->getId().",".$i.")\">";
            ?>
        </div>
        <p>Click <a href="<?= $linkTo('employerHomePage'); ?>">Here</a> to return home.</p>
    </div>
	<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>