
<?php 
include "header.phtml"
 ?>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
				<h2>Employer Registration Form</h2>
			</div>
		<div id="registration">
        <form method="POST" name="registration" action="<?= $linkTo('registrationConfirmationPage'); ?>" >
            <p>Username: <input type="text" placeholder="Username"  name="username" size="40" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only" ></p>
            <p>Email: <input type="text" placeholder="Email" name="email" size="40" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address e.g: example@gmail.com" ></p>
            <p>Password: <input type="password" placeholder="Password" name="password" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" > </p>
            <p>Confirm Password: <input type="password" placeholder="Password" name="password_confirm" size="40" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$" title="Must contain at least one uppercase letter, and be between 7-15 characters" ></p>

            <p>Phone number: <input type=text name="phoneNumber" size="40"> </p>
            <p>Location: <input type=text name="location" size="40"> </p>

            <p>Company Name: <input type=text name="companyName" size="40"> </p>
            <p>URL: <input type=text name="url" size="40"> </p>
            <p>Contact Name: <input type=text name="name" size="40"> </p>
            <p>Contact Phonenumber: <input type=text name="phoneNumber" size="40"> </p>

            </div>
            <p type="hidden" id="validate"></p>
            <button id="submit-registration" value="Register" onclick="return validateForm()">Register</button> 
            <input id="submit-handle" type="submit" style="display: none">
        </form>
		    <br> 	
			
		</div>
	</div>	
	<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>