<?php
    include "header.phtml"
?>
<!---------- Body starts --------------->

	<div class= "page">
		
		<div class = "content">
			<h2>An error occurred.</h2>
			<p>Click <a href="<?= $linkTo('logout'); ?>">Here</a> to return to login page</p>  <!--- Change linkTo depending on routing ---->
		</div>
	</div>

<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>