<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recruitment Portal Ltd</title>
    <link rel="shortcut icon" href="https://nuvo.vesta-central.com/wp-content/uploads/2017/11/square_lg.jpg">


<meta name="keywords" content="Vesta Recruitment Portal" />
<meta name="description" content="A online medium where employers can connect with potential candidates" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />


<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />


    <link rel="stylesheet" type="text/css" href="/static/styles/style.css">
</head>
<body>
<!---------- Header ends --------------->