<?php
session_start();
include "header.phtml"
?>
<!---------- Body starts --------------->


<!--- Content Start -->
<div class= "container-fluid center" id= "page">

    <div class = "content">

        <div class = "title">
            <h2>Password Recovery email sent successfully.</h2>
        </div>
        <div class="partition">
            <br>
            <p>You should receive an email for password recovery</p>
            <p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p>
            <?php
            function gen_uuid() {
    return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        // 32 bits for "time_low"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        // 16 bits for "time_mid"
        mt_rand( 0, 0xffff ),

        // 16 bits for "time_hi_and_version",
        // four most significant bits holds version number 4
        mt_rand( 0, 0x0fff ) | 0x4000,

        // 16 bits, 8 bits for "clk_seq_hi_res",
        // 8 bits for "clk_seq_low",
        // two most significant bits holds zero and one for variant DCE1.1
        mt_rand( 0, 0x3fff ) | 0x8000,

        // 48 bits for "node"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    );
}
$str =  gen_uuid();
            echo "<p>".$str." </p>";

?>
        </div>
        <br>

    </div>
</div>
<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>