
<?php 
session_start();
include "header.phtml"
 ?>
<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			
			<div class = "title">
			<h2>Password Recovery email sent successfully.</h2>
			</div>
			<div class="partition">
				 <br>
				 <p>You should receive an email for password recovery</p>
					<p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p>  <!--- Change linkTo depending on routing ---->
			</div>
			<br>
			<br>
			
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>