<?php
session_start();
include "header.phtml"
?>
<!---------- Body starts --------------->


<!--- Content Start -->
<div class= "container-fluid center" id= "page">

    <div class = "content">

        <div class = "title">
            <h2>Password Recovery email sent successfully.</h2>
        </div>
        <div class="partition">
            <br>
            <p>You should receive an email for password recovery</p>
            <p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p>

        </div>
        <br>

    </div>
</div>
<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>