
<?php 
session_start();
include "header.phtml"
 ?>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
			<h2>Account Password Recovery.</h2>
			</div>
			<div class="partition">
				<form action = "<?= $linkTo('passwordRecovery'); ?>" method="post">
		       		<p>Username: <input type="text" name="username_input" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only"></p>
		       		<input id="login-button" type="submit" value="Login">
		       	</form>
			</div>
			<br>
			
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>