<?php
include "header.phtml"
?>
<!---------- Body starts --------------->


<!--- Content Start -->
<div class= "container-fluid center" id= "page">

    <div class = "content">
        <div class = "title">
        </div>

        <div class="partition small-box-format">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
            <form method="POST" action = "<?= $linkTo('passwordRecovery'); ?>" >
                <div class="form-group">
                    <label for="username">Username: </label>
                    <input class="form-control" type="text" name="username" id="username" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only"></label>
                    <!-- <button id="submit-registration" value="Register" onclick="return validateForm()">Register</button> -->
                </div>
                <div class="center button-pad row">
                    <input class="btn btn-info" id="login-button" type="submit" >
                </div>

            </form>
<!--            <p>Click <a href="--><?//= $linkTo('passwordRecoveryConfirmationPage'); ?><!--">Here</a> to go to the next page(temp)</p>-->
        </div>
        <br>

    </div>
</div>
<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>