<?php
include "header.phtml"
?>
<!---------- Body starts --------------->


<!--- Content Start -->
<div class= "container-fluid center" id= "page">

    <div class = "content">
        <div class = "title">
            <h2>Account Password Recovery.</h2>
        </div>

        <div class="partition">
            <form method="POST" action = "<?= $linkTo('passwordRecovery'); ?>" >
                <p>Username: <input type="text" name="username" required pattern="^[a-zA-Z0-9]+$" title="Alphanumeric characters only"></p>
                <!-- <button id="submit-registration" value="Register" onclick="return validateForm()">Register</button> -->
                <input id="login-button" type="submit" >

            </form>
            <p>Click <a href="<?= $linkTo('passwordRecoveryConfirmationPage'); ?>">Here</a> to go to the next page(temp)</p>
        </div>
        <br>

    </div>
</div>
<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>