
<?php 
session_start();
include "header.phtml"
 ?>

<!---------- Body starts --------------->


	<!--- Content Start -->
    <div class="container-fluid center" id="page">

		
		<div class="partition" id="login">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
			<h4 class="center">Choose Account Type:</h4>
            <div class="center button-pad row">
                <a class="btn btn-info" href="<?= $linkTo('candidateRegisterPage'); ?>">Candidate</a>
            </div>
            <div class="center button-pad  row">
                <a class="btn btn-info" href="<?= $linkTo('employerRegisterPage'); ?>">Employer</a>
            </div>
		</div>
		
		
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>