
<?php 
session_start();
include "header.phtml"
 ?>

<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class = "page">

		
		<div class="partition">
			<p>Please choose which type of account you want to create</p>
			<a class="button" href="<?= $linkTo('candidateRegisterPage'); ?>">Candidate</a>
			<a class="button" href="<?= $linkTo('employerRegisterPage'); ?>">Employer</a>
			<a class="button" href="<?= $linkTo('home'); ?>">Return</a> <!--Remove This -->
		</div>
		
		
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>