
<?php 
session_start();
include "header.phtml"
 ?>
<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class="container-fluid center" id= "page">
		
		<div class="partition ">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
			<div class = "title center">
				<h2>Account created successfully.</h2>
			</div>
            <p>You should receive an email confirming account creation soon.</p>
            <p>Click <a href="<?= $linkTo('home'); ?>"> Here </a> to return back to login page</p>
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>