
<?php 
session_start();
include "header.phtml"
 ?>
<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
<!---------- Body starts --------------->


	<!--- Content Start -->
	<div class= "page">
		
		<div class="partition">
			<div class = "title">
				<h2>Account created successfully.</h2>
			</div>
			 <br>
			 <p>You should receive an email confirming account creation(implementation coming soon)</p>
				<p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p>
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>