<?php
include "header.phtml"
?>

    <script>
        function validatePassword(){
            //Checks to see if the passwords match
            var password = document.forms['registration']['password'].value;
            var password_confirm = document.forms['registration']['password_confirm'].value;

            if (password !== password_confirm) {
                alert('Passwords do not match!');
                return false;
            }
            var submitButton = document.getElementById('submit-handle');
            submitButton.click();
            return true;
        }
    </script>

    <!---------- Body starts --------------->

    <div class= "center container-fluid" id="page">
        <div class="partition small-box-format">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
            <div class="center">
                <h4>Set New Password</h4>
            </div>
            <form method="POST" name="registration"  action="<?= $linkTo('updatePassword'); ?>">
                <br>
                <div class="form-group">
                    <label for="password">Password: </label>
                    <input class="form-control" id="password" size="60" name="password" type="password" placeholder="At least 7 characters and must contain 1 uppercase letter" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$">
                </div>
                <div class="form-group">
                    <label for="password_confirm">Confirm Password: </label>
                    <input class="form-control" id="password_confirm" size="52" name="password_confirm" type="password" placeholder="Retype password" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$">
                </div>
                <input type="hidden" name="uuid" value="<?= $uuid; ?>">

                <div class="center">
                    <!--<button class="btn btn-info"  >Change Password</button> -->
                    <input type="button" class="btn btn-info" id="submit-registration" value="Change Password" onclick="return validatePassword()">
                </div>
                <input id="submit-handle" type="submit" style="display: none">
            </form>

        </div>
    </div>

    <!--- Content Ends here ----------->




    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>