<?php
    include "header.phtml"
?>
<!---------- Body starts --------------->

	<div class= "center container-fluid" id="page">
        <div class="text-center partition small-box-format">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
            <h2>YOU CAN SOON RESET PASSWORD.</h2>
            <p>Click <a href="<?= $linkTo('logout'); ?>">Here</a> to return to login page</p>  <!--- Change linkTo depending on routing ---->
        </div>
    </div>

<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>