<?php
session_start();
include "header.phtml"
?>
<!---------- Body starts --------------->


<!--- Content Start -->
<div class= "container-fluid center" id= "page">

    <div class = "content">

        <div class = "title">
        </div>
        <div class="partition">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
            <h4>Success!</h4>
            <p>Your password has been changed</p>
            <p>Click <a href="<?= $linkTo('home'); ?>">Here</a> to return back to login page</p>

        </div>
        <br>

    </div>
</div>
<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>