<?php
    include "header.phtml"
?>

    <script type = "text/javascript" src="src/js/validateForm.js"></script>
<!---------- Body starts --------------->

	<div class= "center container-fluid" id="page">
        <div class="text-center partition small-box-format">
            <div class="center">
                <img id="logo" src="/static/styles/Images/VN.png">
            </div>
            <form method="POST" action="<?= $linkTo('updatePassword'); ?>">
                <br>
                <div class="form-group">
                     <label for="password">Password: </label>
                    <input id="password" size="60" name="password" type="password" placeholder="At least 7 characters and must contain 1 uppercase letter" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$">
                </div>
                <div class="form-group">
                    <label for="password_confirm">Confirm Password: </label>
                    <input id="password_confirm" size="52" name="password_confirm" type="password" placeholder="At least 7 characters and must contain 1 uppercase letter" required pattern="^(?=.*[A-Z])([a-zA-Z0-9]{7,15})$">
                </div>
                <input type="hidden" name="uuid" value="<?= $uuid; ?>">

                <div class="center">
                    <button class="btn btn-info"  >Change Password</button>
                </div>
                <input id="submit-handle" type="submit" style="display: none">
            </form>

        </div>
    </div>

<!--- Content Ends here ----------->




<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>