<?php 
session_start();
include "header.phtml"
 ?>
    <script type = "text/javascript" src="src/js/populateSubFields.js"></script>
    <script type = "text/javascript" src="src/js/livesearch.js"></script>

	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content" class="container">
			<div class = "title">
				<h2>Search Menu</h2>
			</div>
			<p>Click <a href="<?= $linkTo('employerHomePage'); ?>">Here</a> to return home
            <form>
                <p>All Categories</p>
                <select id="field0" onclick="updateFields()">
                    <?php
                    echo "<option value=\"all\">all categories</option>";
                    foreach ($Fields as $field){
                        echo "<option value=\"".$field['id']."\">".$field['field']."</option>";
                    }
                    ?>
                </select>

                <p>All Sub-Categories</p>
                <select id ="sub-field0" name="sub-field0">
                    <option value="all">All Sub-Categories</option>
                </select>
                <input type="hidden" value="0" name="skill-count" id="skill-count">


            <div id="skills-search-bar">
					<p> Search Skills:  <input id="skill-search" type="text" size="50"></p>
				</div>

                <input id="submit-search" type="button" value="Search" onclick="showResult()">
				<br>

				<div id = "search">
                	<p><b>Search Results</b></p>
                	<div id="livesearch"> </div>
                </div>
              
            </form>
			<br>
		</div>
	</div>
	<!--- Content Ends here ----------->



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>